### ISSUE TITLE
Remove dependency on Elbox's pci.library

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#1]
## Problems
- Currently sonnet.library is relying on a modified version of Elbox's pci.library.
- Currently sonnet.library requires an access to graphics card memory, which in some cases require prior card-specific setup (for example initialisation of memory controller on Voodoo 3).
- Elbox does provide development kit only under restrictive NDA.
  - We don't have an access to that SDK.
  - Such restrictive NDA is incompatible with open source nature of this project.
## Proposed solution
- Write a new, open source implementation of PCI library - codename KlozetPCI.
- Use NetBSD Mediator drivers as a basis.
- Provide bus_space(4)-like API.
- Optionally add a compatibility layer that would allow to use existing drivers (OpenPCI or Elbox pci.library API reimplementation).

**Comment by rkujawa** [comment]
This is being worked on in KlozetPCI project:
https://github.com/Sakura-IT/KlozetPCI

**Comment by DvdBoon** [comment]
Dependency could already be made to a minimum for at least the sonnet card if voodoo3 gfx memory initialization code could be added to the sonnet.library (and other gfx card memory initialization code). However, all other mediator functionality (graphics, network, usb etc.) will still be dependent on the pci.library in this case.

Until now the way to initialize the voodoo3 gfx mem eludes me.

**Comment by rkujawa** [comment]
Did you perhaps investigate the supposed new functionality of pci.library 11.0? I.e. "New pci.library gives the possibility to reallocate (free and allocate) PCI spaces from the driver for the specific PCI card". 

Does the 11.0 library still lock up the system when Sonnet is installed?

**Comment by DvdBoon** [comment]
Not yet. But I can confirm that the Amiga starts up with pci.library 11.0
and a sonnet card installed. No infinite loop during PCI memory allocation
anymore. Sonnet card is correctly identified by pciinfo and the A1200 PPC
setup code starts the PPC processor correctly.

2016-07-20 9:25 GMT+02:00 Radosław Kujawa notifications@github.com:

**Comment by rkujawa** [comment]
Since they have eliminated the problems with startup, maybe it would be possible use stock non-patched pci.library?

**Comment by DvdBoon** [comment]
I think so, yes. I've installed it on my A1200 and also made a quick
posting on EAB about it. Have not tested it running real software yet, but
on the A1200 the amiga starts, pciinfo sees the card correctly and the PPC
boots correctly.

Cannot really run anything on it as I cannot load any software yet (that is
where the mmu library comes in), but the PPC kernel is running.

Op 20 jul. 2016 11:16 a.m. schreef "Radosław Kujawa" <
notifications@github.com>:

**Comment by DvdBoon** [comment]
11.0 seems to work. Also I think I have enough info to replace the pci library on the big box Amigas, but I'm lacking time and it's prioritized rather low on my list.

**Comment by rkujawa** [comment]
In an unexpected turn of events, Elbox started cooperating with Dennis on updating pci.library to fully support Sonnet (and other future accelerators). Therefore this task seem unnecessary and would be a pure waste of resources.
