### ISSUE TITLE
Support initialising graphics card memory from sonnet.library

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#11]
As a temporary solution, we should support initialising graphics card memory from sonnet.library. This is supposed to be a temporary solution since KlozetPCI is not ready to use yet, so that we can avoid using pci.library.

Add support for at least Voodoo 3. I'm digging through the datasheet, I'll see what I can do.

**Comment by DvdBoon** [comment]
Any progress on this? I have to admit that the documentation of the avenger doesn't read as wel as the  motorola docs. However, I have the source of the BeOS VooDoo3 drivers laying around if that helps.

**Comment by rkujawa** [comment]
Not really, other projects getting in the way. I still intend to do it though. 

Toni Willen just implemented emulation of Mediators in WinUAE (with a bit of my help :smile:), this should help me with PCI programming while on the road.

**Comment by rkujawa** [comment]
This does not seem necessary anymore, just as #1.
