### ISSUE TITLE
Patch existing WarpOS applications to place data/code in 0x1005 memory

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#12]
Typical WarpOS applications are linked to place data and code in Fast RAM. For it to be accessible by PPC CPU, it should be placed in memory with attribute 0x1005 (which is Sonnet memory). 

How to patch existing programs? I guess we need some kind of wrapper that takes an executable, patches all PPC hunks and then starts it?

**Comment by rkujawa** [comment]
I started developing a patch utility and wrapper in sonnetrun subdirectory.

**Comment by rkujawa** [comment]
I wrote a hunk executable parser and it seems to work correctly, so next setup would be implementing actual automated patching routine. 

I investigated Extended Hunk Format, but it seems that changes introduced in EHF are only covering object files. Load file format is the same as usual (probably they wanted to avoid modifying AmigaOS hunk file loader). 

We need to patch hunk header of PPC data and code sections. But how can we know which ones are containing PPC code?

@DvdBoon what do you think is the best way determine which hunks should be patched?

**Comment by DvdBoon** [comment]
Currently, code and data hunks contain a mix of PPC code and 68K code. The only way to know if there is any PPC code is that the programs opens powerpc.library. I was thinking of patching the open function of (a dummy) powerpc.library and go from there somehow.

**Comment by rkujawa** [comment]
But even if we do that, how do we know which hunks need to be patched? Do we really have to patch them all? That would slow down 68k a lot.

**Comment by rkujawa** [comment]
Suddenly, sonnetpatch became a sophisticated tool:

```
$ ./sonnetpatch ../tools/getinfo_ppc
HUNK_HEADER
    Hunk table size: 3
    First hunk to load: 0
    Last hunk to load: 2
HUNK_CODE (0x3e9) hunk number 0
    Size: 46 Amiga longwords (184 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x1005
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 1
    Size: 49 Amiga longwords (196 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_DATA (0x3ea) hunk number 2
    Size: 126 Amiga longwords (504 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x1005
```

**Comment by rkujawa** [comment]
The sonnetpatch tool can now patch size header of a specified hunk:
`$ ./sonnetpatch  -pHUNKNUM,HUNKNUM2,...  in_file out_file`

**Comment by DvdBoon** [comment]
Changed it to $2005.

**Comment by DvdBoon** [comment]
I wonder if it is not easier to rename the sonnet.library to powerpc.library, mark WarpOS programs with something special in the hunk header (Overwrite 0x3f3 with some magic number).and install some LoadSeg() patch (maybe taken from the source from ppclibemu and extended with our magic number).

**Comment by DvdBoon** [comment]
Added a LoadSeg() and a NewLoadSeg() patch that scans for the library name in the seglist. If found the file is loaded into PPC memory. Seems to work correctly. Haven't found a failure/slowdown yet.

**Comment by DvdBoon** [comment]
This still needed with the move to system which patches during loading?

**Comment by DvdBoon** [comment]
No longer needed with the phasing out of sonnet.library in favour of the powerpc.library with the LoadSeg() patch.
