### ISSUE TITLE
PPC crash after starting different WarpOS programs

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/SonnetAmiga#14]
During stress-testing of the code, the following issue was detected:

Running different, moderate complex, WarpOS programs in concession crashes the PPC.

For example

1) Start sonnet.library -> any number of Getinfo mixed with any number of CyberPI OR CyberMand
-> Works

2) Start sonnet.library -> mix CyberPI AND CyberMand
-> PPC crashes during the start of the second program (being CyberPi after Cybermand or vice versa)
-->In some occasions, CyberPI runs but calculates PI wrongly.

This can be a memory allocation issue, register transfer issue, program exit code issue or a cache issue. As there are no debuggers for the sonnet available (yet) it takes time to pin-point the exact cause.

**Comment by DvdBoon** [comment]
Bug has been narrowed down to CyberPi. Mixing Getinfo/Cybermand/Landscape does not crash the PPC. I did however find that the first program started after initializing the PPC was in Supervisor Mode. Fixed that.

**Comment by DvdBoon** [comment]
Turning caches off fixes the problem. Probably some cache flush problem.

**Comment by DvdBoon** [comment]
This is actually a major problem. How to maintain cache coherency between the two processors. All the bugs so far can be traced to this problem.

**Comment by rkujawa** [comment]
The problem is that in original WarpOS it was the user application that was responsible for keeping caches consistent. WarpOS API provided a few functions to maintain this. So I am not sure how much of a problem is this with our reimplementation of API, and how much with the application.

Additionally, we have the difference that Sonnet has L2 cache. Original PPC boards had no L2 cache at all. L1 cache was flushed on every context switch (at least in PowerUP, not sure about WarpOS...). It was slow but reliable method.

**Comment by DvdBoon** [comment]
Been doing some reading...

Need to rewrite cache handling for RunPPC(), Run68K(), PutXMsgPPC() (and later for PutXMsg().
Remove cache handling from Super()
Add cache handling for the 68K Enqueue() being performed when a new PPC task is inserted on the shared list (NewTasks)
Add cache handling when the PPC reads/removes from this shared list.
Another shared list is the Sonnet memory header. Need cache handling here too (impacts on AllocVec(PPC) and FreeVec(PPC).

I think that's it.

Now to find the time.

**Comment by DvdBoon** [comment]
A context switch not only needs a flush, but also an invalidate (otherwise stale caches when the other CPU changes stuff; mostly needed on the shared XMsg, some shared stuff on the PPC zero page and Sonnet memory headers). The latter is missing at the PPC side and on the 68K it is used in a wrong way at the moment. Flushing on the PPC side is also not implemented correctly at the moment.

I'd like to finish multitasking first, though (with caches disabled) and then implement the new and improved cache handling.

**Comment by DvdBoon** [comment]
Some first signs of life regarding multitasking (Putting tasks in TS_WAIT/TS_READY/TS_RUN on the PPC side)
![multitask](https://cloud.githubusercontent.com/assets/10966544/7399713/e4da7d9a-eeb7-11e4-94f0-5ac2b986320f.png)

**Comment by rkujawa** [comment]
Cool, it's really exciting to see it being more and more complete.

**Comment by DvdBoon** [comment]
Looking at WarpOS: it avoids coherency problems by doing list manipulations using the 68K. So AllocVecPPC and FreeVecPPC do a call to Run68KLowlevel to change memory allocations through AllocMem and FreeMem from 68K exec. We have a path forwards.

**Comment by DvdBoon** [comment]
Rewriting the message system between the 68k and the PPC at the moment. Interrupts are missed by using a single register to communicate (it gets overwritten by the PPC before the 68K has handled it). Moving to the FIFO message system provided by the MPC/TSi107 chipset.

At the moment the L1 and L2 caches are off of the PPC for debugging purposes.
The PCI memory addressed by the 68K is currently NOCACHE memory set by the MMU.

**Comment by rkujawa** [comment]
I saw the new FIFO-based system, looks rather cool. I wish I knew more about PPC assembly ;).

**Comment by DvdBoon** [comment]
Bug seems to be fixed after the inter-CPU communication update and the Instruction Cache Invalidation (HID0_ICFI) bug.

Working WarpOS progams:

CyberMand, CyberPi, Tabletennis, PixelOMania, Landscape, Voxelspace
