### ISSUE TITLE
Duplicate files in sonnetlib and tools.

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#15]
@DvdBoon 
Some files are duplicated in both directories:
ppcdefines.i
ppcmacros-std.i
Is it safe to move them to one directory, let's say named "common" and just add that directory to include path in both sonnetlib and tools with -I parameter to vasm? It could work this way from both Makefiles and AmigaOS script that you're using. 

I guess it should be fine, but I preferred to ask before moving anything since it's your code ;).

**Comment by DvdBoon** [comment]
Sure :-)

**Comment by rkujawa** [comment]
I've moved that but there's a build failure now, that is probably unrelated to what I have done.

See my comment under e78bb70 commit.

**Comment by rkujawa** [comment]
Ok, after updating it seems to work fine :). Please cvs up my changes.
