### ISSUE TITLE
Not all WarpOS programs are yet compatible

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/SonnetAmiga#18]
I want to document here the programs which are working and which are not. Hopefully in time the first list will get longer and the second one will disappear :-)

The list of working/non-working software is kept in the Wiki:
https://github.com/Sakura-IT/SonnetAmiga/wiki/compatible-software

**Comment by DvdBoon** [comment]
Moved dnetc from partially working to working. Moved AFlops to working.
Moved Quake II to working.
Moved MP3 decoder AmigaAMP to partially working
Moved WarpSCUMM/WarpSDL to partially working.

**Comment by DvdBoon** [comment]
Moved SysSpeed and WhichAmiga to working
Moved WarpAMP and AmigaAMP WOS decoder to working.

**Comment by togflops** [comment]
Tried sonnetpatch on this http://aminet.net/package/gfx/misc/rippleWOS
Doesn't work: bad loadfile hunk, not that it is any big loss, I'm just trying "little" programs.
HUNK_HEADER
    Hunk table size: 4
    First hunk to load: 0
    Last hunk to load: 3
HUNK_CODE (0x3e9) hunk number 0 at offset 0x24ffffffff
    Size: 143 Amiga longwords (572 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 1 at offset 0x268ffffffff
    Size: 7347 Amiga longwords (29388 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 2 at offset 0x7578ffffffff
    Size: 86 Amiga longwords (344 bytes)
    Flags: None (implied MEMF_PUBLIC)
HUNK_DATA (0x3ea) hunk number 3 at offset 0x76f0ffffffff
    Size: 634 Amiga longwords (2536 bytes)
    Flags: None (implied MEMF_PUBLIC)
Unaligned read at 80e400000003!

**Comment by togflops** [comment]
Tried sonnetpatch on this abomination:http://aminet.net/package/util/blank/Fairies
Doesn't work: bad loadfile hunk
HUNK_HEADER
    Hunk table size: 3
    First hunk to load: 0
    Last hunk to load: 2
HUNK_CODE (0x3e9) hunk number 0 at offset 0x20ffffffff
    Size: 89584 Amiga longwords (358336 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 1 at offset 0x577e8ffffffff
    Size: 23203 Amiga longwords (92812 bytes)
    Flags: None (implied MEMF_PUBLIC)
HUNK_DATA (0x3ea) hunk number 2 at offset 0x78998ffffffff
    Size: 12303 Amiga longwords (49212 bytes)
    Flags: None (implied MEMF_PUBLIC)
Unaligned read at 849e000000003!

**Comment by rkujawa** [comment]
Did you forget to pass `-p` parameter to `sonnetpatch`? Running it without parameters is only good for investigating what hunks are in the table.

Besides, see issue #16.

Anyway, I tried to patch rippleWOS:

```
$ ~/repos/sonnetamiga/sonnetrun/sonnetpatch -p0,1,2,3 rippleppc rippleppc.patched
0
1
2
3
HUNK_HEADER
    Hunk table size: 4
    First hunk to load: 0
    Last hunk to load: 3
Unaligned read at 80e4!
HUNK_CODE (0x3e9) hunk number 0 at offset 0x24
    Size: 143 Amiga longwords (572 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 1 at offset 0x268
    Size: 7347 Amiga longwords (29388 bytes)
    Flags: None (implied MEMF_PUBLIC)
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 2 at offset 0x7578
    Size: 86 Amiga longwords (344 bytes)
    Flags: None (implied MEMF_PUBLIC)
HUNK_DATA (0x3ea) hunk number 3 at offset 0x76f0
    Size: 634 Amiga longwords (2536 bytes)
    Flags: None (implied MEMF_PUBLIC)
Patching hunk 0 size to c000008f, ext. attr 2005
Patching hunk 1 size to c0001cb3, ext. attr 2005
Patching hunk 2 size to c0000056, ext. attr 2005
Patching hunk 3 size to c000027a, ext. attr 2005
$ ~/repos/sonnetamiga/sonnetrun/sonnetpatch rippleppc.patched
HUNK_HEADER
    Hunk table size: 4
    First hunk to load: 0
    Last hunk to load: 3
Unaligned read at 80f4!
HUNK_CODE (0x3e9) hunk number 0 at offset 0x34
    Size: 143 Amiga longwords (572 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x2005
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 1 at offset 0x278
    Size: 7347 Amiga longwords (29388 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x2005
    Relocation: HUNK_RELOC32 (0x3ec)
HUNK_CODE (0x3e9) hunk number 2 at offset 0x7588
    Size: 86 Amiga longwords (344 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x2005
HUNK_DATA (0x3ea) hunk number 3 at offset 0x7700
    Size: 634 Amiga longwords (2536 bytes)
    Flags: Extended mem attributes
        Extended memory attribute: 0x2005
```

Here's the patched binary, try it:
http://c0ff33.net/drop/rippleppc.patched

**Comment by togflops** [comment]
I can't try your patched version.
"You don't have permission to access /drop/rippleppc.patched on this server."
Oops you know I didn't run it with -p.  
I did rerun it with -p0,1,2,3 but file is not executable.

**Comment by rkujawa** [comment]
Sorry, I forgot to give the right permissions to rippleppc.patched. You should be able to download it now (if it still displays the same permission denied, then reload that page).

The resulting file is not executable? Maybe a simple `protect file +e` will fix that? `sonnetpatch` does nothing related to AmigaOS permissions.

**Comment by togflops** [comment]
Yes I downloaded it now.  "Unable to open powerpc.library"  it said it is WoS.  But it tried to run at least

**Comment by rkujawa** [comment]
Ah, I guess you'd also need to change all occurrences of `powerpc.library` to `sonnet.library` in the executable. `sonnetpatch` doesn't do that yet.

Created issue #22 to track this.

**Comment by togflops** [comment]
You were right about the attributes -R -E were set.

**Comment by togflops** [comment]
http://aminet.net/package/driver/video/RTGoesWarpOS
This worked with sonnetpatch, again the resulting file was read only for some reason.  But it seems to work with the rtgmaster demos.  -Update- I thought that this was working selecting this as the C2P mode let the demos run, it says that the improvement is slight so I thought it was working-it is not.  The RTGMaster libraries check for PowerPC.library before running in PPC mode, so the RTGMaster libraries need patching before this will work.

**Comment by togflops** [comment]
http://aminet.net/package/misc/emu/SavagePPC
Sonnetpatch seemed to work, but Shapeshifter says the external video driver could not be used.  However I notice the file type is "Project" while the original was "Tool"  again it set -E -R.

**Comment by togflops** [comment]
Some more interesting programs:
Ifusion  (I can dream right? :)
WarpSnes http://aminet.net/package/misc/emu/warpsnes-wos
MAME http://amidog.com/amiga/mame/index.html  (snoopdos shows this is calling powerpc.library)
Moovid

**Comment by DvdBoon** [comment]
Added RippleWOS to partly working. It does not quit on CTRL-C

**Comment by DvdBoon** [comment]
Added WipeOut 2097 to working
Added Earth2140 to working
Added Warp3D-PPC to working
Added Payback PPC to NOT working

**Comment by rkujawa** [comment]
I'm moving the list of working/non-working software to the Wiki. We can still keep this issue open to track technical issues.

**Comment by DvdBoon** [comment]
Payback uses the stbx instruction to access CHIP memory. This instruction is not yet emulated by the CHIP/FASTMEM access handler in the sonnet.library

**Comment by DvdBoon** [comment]
I have a prgram which uses $0 as a buffer: Starts with:

nop
lis r11,0
stw r1,0(r11)

As the sonnet library stores values here, the library crashes. I wonder if it is common practice to use location $0. (Offending program Vice_WOS in this case).

I am planning to move everything what is needed by code in user mode from the zero page to lib base. Supervisor code will still have access to the zero page. (User accesses to zero page are diverted to the zero page of the 68k).

**Comment by rkujawa** [comment]
This is a bit weird... Why would anyone do that?

I found this screenshot of Vice WarpOS:
http://www.amigarulez.de/ebay/WOS_Exception.jpg

Looks like a bug to me - crashes even on original WarpOS.

**Comment by DvdBoon** [comment]
Ah ok, it's off the list then. I won't bother with it.

**Comment by DvdBoon** [comment]
PPCLibemu seems to work to some extent. Some basic PowerUp programs now work.

**Comment by DvdBoon** [comment]
Two big features of the powerpc.library left in order of priority:

1) Exception handlers. 2 have been fully implemented to make wosdb work, 6 are untested, 4 are not yet implemented (needed for iFusion). Those are DEC, EE, DSI and Alignment.
2) Advanced MMU functions. Needed for stuff like memory protection. Not planned to be implemented into the library.

**Comment by DvdBoon** [comment]
Still left to do regarding compatibility

1) PP_STACKPTR/PP_STACKSIZE support for Run68K()
2) Alignment support in AllocVecPPC()

Much further down on the priority list:

3) Advanced MMU support in AllocVecPPC()

**Comment by DvdBoon** [comment]
1 and 2 were implemented in 183/185. Further compatibility will be tracked in the wiki or in a separate issue tracker
