### ISSUE TITLE
Dependency on DevPac system library.

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#19]
I wanted to plug InitSonnet into our build system. Basically I've done the necessary adjustments, but do we really need that DevPac system library? It makes requirements on external stuff even more complex than it already is. If possible, I'd like to keep them at minimum.  What does InitSonnet really use that is there? Can we just copy^Wreimplement the necessary routines and put them in our tree?

**Comment by DvdBoon** [comment]
I use system.gs (which is just a big table made of all the common NDK includes) because it saves me from finding out which includes to use separately (a.k.a. lazy). I fixed the source, though. Could you check it out if it compiles?

**Comment by rkujawa** [comment]
I had to make a few minor changes related to includes. See 84b6c72fbbfff2359bf86f84268d7fb9382d90bf. Shouldn't sonnet_lib.i be moved to `common` directory in this case? Or `sonnetlib` added to `-I` flag when assembling?

The rest is just boring Makefile cruft. It does compile now as a part of standard build.

**Comment by DvdBoon** [comment]
If you want it to be in-line with the assembling of the library then please add common to the -I flag. I kept it the same as with sonnet.s. Or did we change that somewhere in the past?

**Comment by DvdBoon** [comment]
Oops, I now see what you mean. Maybe move all this stuff to common?

**Comment by rkujawa** [comment]
If by this stuff you mean the `.i` files, then I think it's probably a good idea. Please do. 

I'll adjust the Makefiles if necessary. Although it should just work since `-I` passed when building InitSonnet already includes `common` directory. It might break somewhere else though. Guess we won't know until we try :stuck_out_tongue: .

**Comment by DvdBoon** [comment]
Moved it. Probably breaks the library itself.

**Comment by DvdBoon** [comment]
Oooh, quite the spectacular breakage :-P

**Comment by rkujawa** [comment]
Even I am not sure why `make` suddenly wanted to call `as` instead of `vasm`. Anyway I fixed it and committed just now. If the next build passes, it means it's OK.

**Comment by rkujawa** [comment]
Looks like it's OK. I'm closing this.
