### ISSUE TITLE
Implement Jenkins for automated builds

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#20]
Currently automated builds are done with a hand-crafted script. Long story short, it sucks. Implement Jenkins to control the build process, report, store history, alert via mails etc. etc. 

http://jenkins-ci.org/

**Comment by rkujawa** [comment]
Working on that, already installed dependencies and the RPM package itself.

**Comment by rkujawa** [comment]
Done! Jenkins can be accessed via the following URL:
https://sonnet.uguu.waw.pl/jenkins/

@DvdBoon Please check if you can log in.

Credentials same as for CVS. Any commit to CVS will automatically trigger Jenkins build. Also, Jenkins should spam the person who broke the build, in case that happens. Though I didn't test that yet.

**Comment by DvdBoon** [comment]
Look like it works. I can log in.

Now to know what I can do with it :-)

Dennis.

2015-12-05 17:13 GMT+01:00 Radosław Kujawa notifications@github.com:

**Comment by rkujawa** [comment]
Basically it replaces the old build script on the server, but has several advantages:
- Jenkins will attempt to build the project. The good thing is that it will happen immediately upon committing to CVS (the old script just polled the repository for changes every 15 minutes).
- You can schedule the build manually if you ever need to ("build now" button in Jenkins).
- If the build is broken, a mail notification will be sent, but only a person who broke the build will get the mail.
- There's a nice history of builds, along with the information whether they passed or not. And of course the resulting `sonnet.lha` archive is attached with every build.
- CVS log history is related to build history, so upon clicking a build you can see a list of CVS changes that are included in this build (of course this works only for builds triggered by commits).
- If we'll ever have any kind of automated tests (like running sonnet.library in emulator), these will also be easy to plug into Jenkins.
