### ISSUE TITLE
The sonnetpatch should fix references to powerpc.library

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#22]
If the user tries to run a binary referencing `powerpc.library`, he'll just get the error message saying it was not found. The `sonnetpatch` utility should be able to change these references to use `sonnet.library` instead.

**Comment by rkujawa** [comment]
Also, note that strings `powerpc.library` and `sonnet.library` are different length. This might require further patching of hunk headers, or padding the hunk where library is referenced.

**Comment by DvdBoon** [comment]
I would recommend only patching powerpc.library,$00 to sonnet.library,$00,$00 for now in combination with the "fast" option. Other strings, like a message for when the library cannot be opened are not critical. E.g. powerpc.library ending with $20, $0A or "!"

**Comment by DvdBoon** [comment]
This still needed with the move to system which patches during loading?

**Comment by DvdBoon** [comment]
SonnetPatch no longer needed with the new powerpc.library LoadSeg() patch.
