### ISSUE TITLE
Unsupported relocation type R_PC error with vlink snapshot 2016-01-21

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#27]
The new vlink version (source snapshot as of two days ago) fails to link library with the following error:

```
Error 32: Target amigahunk: Unsupported relocation type R_PC (offset=0, size=16, mask=ffffffffffffffff) at LibBody+0x1ea.
```

Investigating.

**Comment by rkujawa** [comment]
Quoting Frank: there is probably a 16-bit PC-relative reference between two different sections somewhere. In the past vlink automatically merged those sections, but over the years I got the impression that this is rarely wanted and often caused by an error.

The vlink has new option -mrel, that instructs the linker to merge all sections with PC-relative references between them. This was done automatically in previous versions, but makes no sense for most targets.

For now I just added -mrel, but we should investigate whether this behaviour is really wanted in our case.

**Comment by rkujawa** [comment]
This makes the project build again with both new vasm (68k & ppc) and vlink on the server.

@DvdBoon What's your opinion on this?

**Comment by DvdBoon** [comment]
The 68k section does a relative (pc) fetch of the start of the ppc code which is in another section. Maybe this can be rewritten

**Comment by rkujawa** [comment]
It's not a problem if it is a desired behaviour, we can just keep -mrel passed to the new vlink and it will work. Please update source, and check if you can build with the new vlink (just added -mrel in last commit).

**Comment by DvdBoon** [comment]
I use a different method in the templates (32 bit relocation) I guess that is the desired method.

**Comment by DvdBoon** [comment]
Building locally works with the fix.
