### ISSUE TITLE
IRA does not like 1005 hunk

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#4]
While investigating optimisations issues, I discovered it is impossible to use IRA on binaries generated with the new version of vasm and vlink (with the memory attribute set to $1005).

Running IRA on such binary results in:
`Hunk...:00001005  NOT SUPPORTED.`

I'll report this issue to author of IRA and ask him to add support for such hunks.

**Comment by rkujawa** [comment]
Frank agreed to implement it.

**Comment by rkujawa** [comment]
Newest source code release (2.09 beta) supports it. Available here:
http://sonnet.uguu.waw.pl/ira/
Still needs some testing.

**Comment by DvdBoon** [comment]
Are all relevant hunks now supported? ($3E9, $3EA, $3EB)? I know we only talked about the code and data hunk, but not about the BSS hunk.

**Comment by rkujawa** [comment]
Looks like BSS is supported too. 

I'm more concerned about PPC code, have to do some more testing, but I think it sometimes is trying to disassemble the PPC code instead of treating it as data. I added disassembly to the build process. 

`make disasm68k` runs ira on all interesting executables.

The result is later archived into disasm68k.lha by the build script (perhaps it should be a make target too). 

See the latest build results: http://sonnet.uguu.waw.pl/builds/20150316-2037/ esp. disassembly of template and getinfo_ppc. It does not look correct to me, but maybe I am doing something wrong ;).

**Comment by DvdBoon** [comment]
I always have to fine-tune ira (using a config file) to get exactly what I want, so I am not surprised :-)

**Comment by DvdBoon** [comment]
This still needed with the move to system which patches during loading?

**Comment by DvdBoon** [comment]
No longer needed as the special hunks will be phased out in favour of the LoadSeg() patch.
