### ISSUE TITLE
Incorrect version string format

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#41]
All the $VER strings should follow the format described in Amiga Developer Docs.

http://amigadev.elowar.com/read/ADCD_2.1/AmigaMail_Vol2_guide/node0011.html

This is certainly the right format for AmigaOS 3.1. Later AmigaOS versions added ability to use 4 digit year and a comment in version string. But I think we should stick to OS 3.1 format, since that's the lowest version of AmigaOS where our implementation of powerpc.library can function correctly.

**Comment by DvdBoon** [comment]
Adjusted to 3.1 syntax.
