### ISSUE TITLE
Programs crash when PCI memory is not cache inhibited on the 68K side.

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/SonnetAmiga#43]
It may be an idea to flush the 68K caches properly when doing a context switch from 68K to PPC. There are actually only a few points in the code where a flush needs to be: In the Run68K code on the 68K side and when sending a packet to the PPC.

Not sure how this will influence overall speed of the context switch. Maybe make it an option. Maybe use the mmu.library in the sonnet library to set things directly instead of a config file?

**Comment by rkujawa** [comment]
In my opinion it certainly makes sense to use `mmu.library` to do that. That would simplify configuration for the user somewhat.

The question is whether we want to make `mmu.library` a necessary dependency to run SonnetAmiga.

**Comment by DvdBoon** [comment]
Not sure.

If mmu library is installed without the sonnet active. the whole PCI memory range will be configured as cache inhibited. Any memory which is in the MemList of Execbase (except CHIP) will be configured as copyback. As the memory of the sonnet is in this list after starting the library, it will be set as copyback by the mmulib installation program.

So if people adhere to that, no dependency on mmu.library is needed.

It would be even easier if the sonnet library didn't care whether it was cache inhibited or copyback (except for the speed). So I guess I'll try to fix that first and then think about mmu.library.

**Comment by DvdBoon** [comment]
Just a general observation:

Everything is really lazy: So on the 68K side, everything is cache-inhibited, on the PPC side every read or write from the 68K triggers a bus snoop and a cache update (for the current cards).

This seems to work.

**Comment by DvdBoon** [comment]
Further support, for example through the mmu.library, will not be implemented in this version of the library. Refer to https://github.com/Sakura-IT/PowerPCAmiga for any further support in the future in the new C version of the library.
