### ISSUE TITLE
Supporting of Killer Xeno Pro and Killer 2100 using PCI to PCIe adapter card

### ISSUE THREAD

**Issue by transi01** [Sakura-IT/SonnetAmiga#47]
Hi Guy's,

would be great if you think about supporting the Killer Xeno Pro and Killer 2100 PCIe cards using PCI to PCIe adapter. The cards do have a 400MHz CPU (dual?) and 128MB of DDR2 Memory on board. Would be a great and cheap upgrade!

I would be happy to help supporting the cards cause I already own one so I'm able to do tests with it!

// Thomas

**Comment by rkujawa** [comment]
This is a duplicate of issue #46.
