### ISSUE TITLE
New vlink crashes on AmigaOS

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#5]
@DvdBoon is having problems running the new version of vlink (current source as of 2015-03-03) on his AmigaOS system.

While linking the executable, proper binary is generated by vlink, but 8000 0004 is thrown upon exit. Apparently the cause is a jump to -186(a6) with a6 being 0.

No issues were noticed on a Linux build server. I'll try to reproduce this on my AmigaOS system and then report the problem to vlink author.

**Comment by rkujawa** [comment]
I built vasmm68k_mot and vlink from current sources, natively on AmigaOS with latest stable vbcc. I can't reproduce the problem you are having.

@DvdBoon please test these binaries:
http://c0ff33.net/drop/sonnetamiga-issue6/vlink
http://c0ff33.net/drop/sonnetamiga-issue6/vasmm68k_mot

If the problem appears with these binaries too, it might be something specific to your setup (or maybe there's a bug triggered only on some configurations).

**Comment by DvdBoon** [comment]
The vlink binary you provided worked. Can you also build the vasmppc_std binary? I don't know why vlink didn't build correctly so I don't trust vasm either to have been build correctly on my system.

Difference between both vlinks is 4 bytes and somehow my vlink has $4e71 on many many addressess where yours has $0000

**Comment by DvdBoon** [comment]
A rebuild against a fresh NDK3.9 and/or the provided vlink here fixed the problem. Vlink now works, alebeit 4 bytes smaller than the one provided here.
