### ISSUE TITLE
PRPMC800-1251 ShowConfig and PCIInfo results

### ISSUE THREAD

**Issue by LevelBest-2004** [Sakura-IT/SonnetAmiga#50]
I have 2 PRPMC800-1251 boards with PMC239/F carrier cards.  These boards feature 128mb RAM.  Mediator would normally have the WinSize jumper open with less than 256mb RAM, but InitPPC will not run unless jumper is closed.  With it closed, the boards are working, but I've noticed that ShowConfig describes them having 512mb RAM, and wonder if this mismatch of pci memory space contributes to stability issues of Apocalypse.  I am also observing that pciinfo reports mine with Vendor ID $1057 but Device ID: $480b with DeviceName unknown instead of MPC107 and doesn't list a MemSpace address.  I've checked the latest vendor.txt from Elbox and it does not include this device ID.   GetInfo results and Warp working, and not sure significance of these observations.  I had jumpered the boards 11-12 as closed because I'd read to somewhere, but cannot recall what the jumper setting does.  Hoping for clarification from someone with more expertise, or possibly share something that may improve the compatibility.

**Comment by DvdBoon** [comment]
Showconfig probably shows the Zorro space in use by the mediator, not the pci card itself. That is what pciinfo is for. If no memory ranges are shown at the apocalypse entry, then initppc was not run. And the card is not a mpc107 card and therefore does not identify as one. 

The jumper prevents local ROM to start up the card which prevents powerpc.library to run correctly on the apocalypse.

Compatibility is not the same as stability. The latter is influenced by the used cpu library and power supply units.

**Comment by LevelBest-2004** [comment]
Sorry you're right.  The setup guide shows memspace in the example before instructing to run initppc, so i figured it appears anyway.  The $480b is returned by Harrier and it is working.. so I don't think I have anything to worry about then.  Thank you for the response and -great- work you all have done!

Sent from Blue<http://www.bluemail.me/r?b=15726>
On Jan 23, 2020, at 5:34 PM, DvdBoon <notifications@github.com<mailto:notifications@github.com>> wrote:

Showconfig probably shows the Zorro space in use by the mediator, not the pci card itself. That is what pciinfo is for. If no memory ranges are shown at the apocalypse entry, then initppc was not run. And the card is not a mpc107 card and therefore does not identify as one.

The jumper prevents local ROM to start up the card which prevents powerpc.library to run correctly on the apocalypse.

Compatibility is not the same as stability. The latter is influenced by the used cpu library and power supply units.
