### ISSUE TITLE
Remote Acces cards with low end ppc?

### ISSUE THREAD

**Issue by AdaptiveSystemsUK** [Sakura-IT/SonnetAmiga#52]
any chance you'd support these - is that even possible?

IBM Remote Supervisor Adapter PCI Card
seem fairly common on ebay, not super expensive, and also have a LAN and mobile Radeon VGA onboard....
i have one i can send you if there is a possiblilty of you getting it working

https://www.ibm.com/support/pages/overview-remote-supervisor-adapter-ii

cheers
AdaptiveSystemsUK

**Comment by rkujawa** [comment]
The integrated 405 core (Book E) is programmatically much different from 60x/G3/G4, so that seems like a lot of work. Besides, I doubt the documentation for IBM's ASIC on this card is even available. A lot of reverse engineering would be required to boot any custom code on this card.

**Comment by DvdBoon** [comment]
I would like to try it, if:

1) Documentation is available on the used PCI-CPU bridge.
2) If these cards have a standard FPU. PPC4xx lack built-in FPUs and they need to be added as a co-processor (APU interface)

**Comment by AdaptiveSystemsUK** [comment]
is this it?
https://elinux.org/images/c/cc/Ppc405gp.pdf
https://elinux.org/images/1/1d/Ppc405gp-errata.pdf
https://www.amcc.com/MyAMCC/retrieveDocument/PowerPC/405GP_GPR/PPC405GP_UM2005_v1_02.pdf

judging by this documentation, the pci bridge is on the cpu - soc?



it has a bcm 5221a4kpt looks like an ethernet controller
https://html.alldatasheet.com/html-pdf/509491/BOARDCOM/BCM5221A4KPTG/786/2/BCM5221A4KPTG.html

https://www.alldatasheet.com/datasheet-pdf/pdf/112430/CYPRESS/CY2292.html

https://datasheetspdf.com/pdf/196095/CypressSemiconductor/CY7C64613/1


is here anything useful that this could do for the amiga community?
as dma controller for pci, for general increased pci bus speeds?
potentially a fast ethernet that works at fast ethernet speeds?

**Comment by DvdBoon** [comment]
Point 2 is the real deal-breaker

**Comment by DvdBoon** [comment]
Also some of the other cards already supported have ethernet and usb on them. Feel free to write a driver for them :)

**Comment by AdaptiveSystemsUK** [comment]
would if i knew how....lol
any good tutorials on things like this?
where would i even start?


yeah, i saw some usenet post about how there is an fpu emulation  in the
xylinx fpga is uses, so not much use, i dont think.

oh well. i only spent £8 on 2 cards. wonder if they'll actually allow
remote access on my old pc....lol

**Comment by AdaptiveSystemsUK** [comment]
next probably stupid  question, hve you guys trid the killernic xeno pro /
2100, using a pci>pcie bridge?
https://www.startech.com/en-eu/cards-adapters/pci1pex1#overview-applications

just looking for a cheap ppc option tbh.

**Comment by DvdBoon** [comment]
Yes, I tried. The Prometheus library (soon to appear on this git) was fixed to also be able to use PCI-PCIe bridges. So I can see the PCIe card and its config register just fine. However, the memory on the card (should be 128MB) does not seem to be reachable. Only the 4MB firmware and some 64K of writable RAM is shown. Not sure what the problem is.

**Comment by DvdBoon** [comment]
This library is no longer in active development. No further actions on this.
