### ISSUE TITLE
Section memory attributes not working for ppc $3E9 (code) hunk

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/SonnetAmiga#7]
vasmppc_std/vlink cannot handle the memory attributes assigned to a code section.

For example:

.section "ppccode","acrx",0x1005

does not work.

**Comment by rkujawa** [comment]
Confirmed, will pester Frank to add this.

**Comment by rkujawa** [comment]
Frank agreed to implement it.

**Comment by rkujawa** [comment]
This is supported in the latest vasm and vlink source code snapshot. I'll proceed with the toolchain upgrade on the server.

**Comment by rkujawa** [comment]
Toolchain on the server updated, the template binary now builds correctly.
