### ISSUE TITLE
Make it possible to run PPC code from graphics card memory

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/SonnetAmiga#8]
Currently graphics card memory is only used to boot the PowerPC CPU. Executing PowerPC programs requires memory installed on the Sonnet board. 

Sonnet Crescendo 7200 has 3 slots that accept 5V, 64-bit-wide, 168 pin, fast-page mode, and 70 ns or faster DIMMs. They are quite difficult to find these days, so an alternative method to run the code should be provided.

It would be nice if we could also use graphics card memory (in case where no Sonnet memory is installed) to run the PPC programs from it.

**Comment by DvdBoon** [comment]
I think graphics memory initialization code is a prerequisite for this. And probably not an option for the Voodoo3 (maybe Voodoo4) cards due to lack of memory. Radeon cards however have enough memory.

**Comment by rkujawa** [comment]
This issue depends on completing issue #11 or #1.

**Comment by DvdBoon** [comment]
The PPC can now run programs from graphics card memory (tested with Quake 1 with the extra pak1.pak). However, it can still not setup the library in it. To facilitate all this, the MEMF_PPC has been changes from $1000 ($1005) to $2000 ($2005) which is the same as the pci.library uses for its memory allocation of pcidma memory.

**Comment by DvdBoon** [comment]
I think this is an unattainable feature as the code gets messed up with an endian change of the screen mode. As soon as a switch is made from a PC mode to a non-PC mode, for example, the code can no longer be executed.

**Comment by DvdBoon** [comment]
1) This can be only done with a Radeon GFX card (so no Warp3D) as 3DFX cards don't have enough memory
2) LE screens should be blocked somehow (endian change messes up the gfx memory)

I'm tempted to close this issue as 'not going to happen'.

**Comment by DvdBoon** [comment]
Will not be implemented due to Endian issues.
